### ISSUE TITLE
infografia

### ISSUE THREAD

**Issue by 27Fer12** [SistemasTecTlaxiaco/actividad-1-infografia-27Fer12-1#1]
[infografia_Fernanda.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-27Fer12-1/files/14252006/infografia_Fernanda.pdf)

**Comment by carlos0716c** [comment]
Calificación conforme a la rúbrica:
1. Partes de la infografía: 4 puntos.
2. Coherencia y pertinencia: 3 puntos.
3. Organización de la información: 4 puntos.
4. Diseño de la infografía: 4 puntos.
5. Creatividad: 4 puntos.
calificación total: 19 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
